#include<bits/stdc++.h>
using namespace std;constexpr int MN=1e6+15,INF=0x3f3f3f3f;struct Edge{int v,w;};int n,m,q,fa[32][MN],fa2[32][MN],dep[MN],f[32][MN][3][3],col[MN][3],ret[2][3],lst[2],pos[2];vector<Edge>adj[MN];namespace ly{namespace IO{
#ifndef LOCAL
constexpr auto maxn=1<<20;char in[maxn],out[maxn],*p1=in,*p2=in,*p3=out;
#define getchar()(p1==p2&&(p2=(p1=in)+fread(in,1,maxn,stdin),p1==p2)?EOF:*p1++)
#define flush()(fwrite(out,1,p3-out,stdout))
#define putchar(x)(p3==out+maxn&&(flush(),p3=out),*p3++=(x))
class Flush{public:~Flush(){flush();}}_;
#endif
namespace usr{template<typename type>inline type read(type&x){x=0;bool flag(0);char ch=getchar();while(!isdigit(ch))flag^=ch=='-',ch=getchar();while(isdigit(ch))x=(x<<1)+(x<<3)+(ch^48),ch=getchar();return flag?x=-x:x;}template<typename type>inline void write(type x){x<0?x=-x,putchar('-'):0;static short Stack[50],top(0);do Stack[++top]=x%10,x/=10;while(x);while(top)putchar(Stack[top--]|48);}inline char read(char&x){do x=getchar();while(isspace(x));return x;}inline char write(const char&x){return putchar(x);}inline void read(char*x){static char ch;read(ch);do*(x++)=ch;while(!isspace(ch=getchar())&&~ch);}template<typename type>inline void write(type*x){while(*x)putchar(*(x++));}inline void read(string&x){static char ch;read(ch),x.clear();do x+=ch;while(!isspace(ch=getchar())&&~ch);}inline void write(const string&x){for(int i=0,len=x.length();i<len;++i)putchar(x[i]);}template<typename type,typename...T>inline void read(type&x,T&...y){read(x),read(y...);}template<typename type,typename...T>inline void write(const type&x,const T&...y){write(x),putchar(' '),write(y...),sizeof...(y)^1?0:putchar('\n');}template<typename type>inline void put(const type&x,bool flag=1){write(x),flag?putchar('\n'):putchar(' ');}}
#ifndef LOCAL
#undef getchar
#undef flush
#undef putchar
#endif
}using namespace IO::usr;}using namespace ly::IO::usr;void dfs1(int u,int pre){if(fa2[0][u])return;fa[0][u]=pre;for(int i=1;i<=30;i++){fa[i][u]=fa[i-1][fa[i-1][u]];}fa2[0][u]=u;fa2[1][u]=pre;for(int i=2;i<=30;i++){fa2[i][u]=fa2[1][fa2[i-1][fa2[i-1][u]]];}for(auto e:adj[u]){if(e.v!=pre){dfs1(e.v,u);if(!col[e.v][0])col[e.v][0]=e.w;else if(!col[e.v][1])col[e.v][1]=e.w;else if(!col[e.v][2])col[e.v][2]=e.w;}}}void dfs2(int u,int pre){if(dep[u])return;dep[u]=dep[pre]+1;for(int a=0;a<3;a++)for(int b=0;b<3;b++)if(a!=b)f[0][u][a][b]=-INF;for(int i=1;i<=30;i++)if(fa[i][u]){for(int x=0;x<3;x++)if(col[u][x]){for(int y=0;y<3;y++)if(col[fa2[i][u]][y]){for(int A=0;A<3;A++)if(col[fa2[i-1][u]][A]){int tmp1=f[i-1][u][x][A];if(tmp1>=0){for(int B=0;B<3;B++)if(col[fa[i-1][u]][B]){int tmp2=f[i-1][fa[i-1][u]][B][y];if(tmp2>=0){int val=tmp1+tmp2+(col[fa2[i-1][u]][A]!=col[fa[i-1][u]][B]);f[i][u][x][y]=max(f[i][u][x][y],val);}}}}}}}for(auto e:adj[u])if(e.v!=pre)dfs2(e.v,u);}int query(int x,int y){if(dep[x]>dep[y])swap(x,y);memset(ret,0,sizeof(ret));memset(lst,0,sizeof(lst));for(int i=30;i>=0;i--){if(dep[fa[i][y]]>=dep[x]){if(!lst[1]){for(int a=0;a<3;a++)for(int b=0;b<3;b++)ret[1][b]=max(ret[1][b],f[i][y][a][b]);lst[1]=fa2[i][y];}else{int tmp[3]{};for(int a=0;a<3;a++)if(col[lst[1]][a]){for(int b=0;b<3;b++)if(col[y][b]){for(int c=0;c<3;c++)if(col[fa2[i][y]][c]){int val=ret[1][a]+f[i][y][b][c]+(col[lst[1]][a]!=col[y][b]);tmp[c]=max(tmp[c],val);}}}memcpy(ret[1],tmp,sizeof(tmp));lst[1]=fa2[i][y];}y=fa[i][y];}}if(x==y){int ans=0;for(int i=0;i<3;i++)ans=max(ans,ret[1][i]);return ans;}pos[0]=x;pos[1]=y;for(int i=30;i>=0;i--){if(fa[i][x]!=fa[i][y]){for(int j=0;j<2;j++){if(!lst[j]){for(int a=0;a<3;a++)for(int b=0;b<3;b++)ret[j][b]=max(ret[j][b],f[i][pos[j]][a][b]);}else{int tmp[3];memset(tmp,128,sizeof(tmp));for(int a=0;a<3;a++)if(col[lst[j]][a]){for(int b=0;b<3;b++)if(col[pos[j]][b]){for(int c=0;c<3;c++)if(col[fa2[i][pos[j]]][c]){int val=ret[j][a]+f[i][pos[j]][b][c]+(col[lst[j]][a]!=col[pos[j]][b]);tmp[c]=max(tmp[c],val);}}}memcpy(ret[j],tmp,sizeof(tmp));}lst[j]=fa2[i][pos[j]];pos[j]=fa[i][pos[j]];}}}int i=0;for(int j=0;j<2;j++){if(!lst[j]){for(int a=0;a<3;a++)for(int b=0;b<3;b++)ret[j][b]=max(ret[j][b],f[i][pos[j]][a][b]);}else{int tmp[3];memset(tmp,128,sizeof(tmp));for(int a=0;a<3;a++)if(col[lst[j]][a]){for(int b=0;b<3;b++)if(col[pos[j]][b]){for(int c=0;c<3;c++)if(col[fa2[i][pos[j]]][c]){int val=ret[j][a]+f[i][pos[j]][b][c]+(col[lst[j]][a]!=col[pos[j]][b]);tmp[c]=max(tmp[c],val);}}}memcpy(ret[j],tmp,sizeof(tmp));}lst[j]=fa2[i][pos[j]];pos[j]=fa[i][pos[j]];}int ans=0;for(int a=0;a<3;a++)for(int b=0;b<3;b++)ans=max(ans,ret[0][a]+ret[1][b]+(col[lst[0]][a]!=col[lst[1]][b]));return ans;}int main(){freopen("trip.in","r",stdin);freopen("trip","w",stdout);read(n,m);for(int i=1;i<=m;i++){int u,v,w;read(u,v,w);adj[u].push_back({v,w});adj[v].push_back({u,w});}dfs1(1,0);dfs2(1,0);read(q);while(q--){int x,y;read(x,y);put(query(x,y));}return 0;}
